<body style="background-color: #aaa;">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!"><b>Books</b></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
             data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
              aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link" href="/admin">Home</a></li>
                    <li class="nav-item"><a class="nav-link" href="/admin/blog">Books</a></li>
                    <li class="nav-item"><a class="nav-link" href="/admin/order">Orders</a></li>
                    <li class="nav-item"><a class="nav-link" href="/admin/user">Users</a></li>
                </ul>
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-5">
                    <li class="nav-item"><a class="nav-link btn" href="/login">SignOut</a></li>
                </ul>
                <form class="d-flex">
                </form>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Books Panel</h1>
                <p class="lead fw-normal text-white-50 mb-0">Books Manage Here</p>
            </div>
        </div>
    </header>
    <!-- Section-->
    <main class="my-5">
        <div class="container">
            <!--Section: Content-->
            <section class="text-center">
                <h4 class="mb-5 p-4"><strong>Your's Books</strong></h4>
                <form action='/admin/update?id=<?php echo $data['_id'] ?>' method="POST">
                    <div class="row my-4">
                        <div class="col-md-3 col-sm-12">
                            <label for="title">Title:
                                <input type="text" name="title" id="title"
                                value="<?php echo $data["title"] ?>">
                            </label>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <label for="data">Price:
                                <input type="number" name="data" id="data"
                                value="<?php echo $data["data"] ?>">
                            </label>
                        </div>
                        <div class="col-md-4 col-sm-8">
                            <label for="image">Image:
                                <input type="text" name="image" id="image"
                                value="<?php echo $data["image"] ?>">
                            </label>
                        </div>
                        <div class="col-md-1 col-sm-4">
                            <input type="submit" class="btn btn-success" value="Update">
                        </div>
                    </div>
                </form>
                <?php
                    if ($_GET['msg'] == "fill_all") {
                        echo "<p class='text-center' style='color: red;' id='error'><b>Fill All Input</b></p>";
                    }
                ?>

            </section>
            <!--Section: Content-->

        </div>
    </main>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p>
        </div>
    </footer>
</body>