<body>
    <?php
    require_once APP_PATH . '/views/header.phtml'
    ?>

    <!--Main Navigation-->

    <!--Main layout-->
    <main class="my-5">
        <div class="container">
            <!--Section: Content-->
            <section class="text-center">
                <h4 class="mb-5 p-4"><strong>Your's Books</strong></h4>
                <form action="/blog/add" method="POST">
                    <div class="row my-4">
                        <div class="col-md-3 col-sm-12">
                            <label for="title">Title:
                                <input type="text" name="title" id="title">
                            </label>
                        </div>
                        <div class="col-md-4 col-sm-12">
                            <label for="data">Price:
                                <input type="number" name="data" id="data">
                            </label>
                        </div>
                        <div class="col-md-4 col-sm-8">
                            <label for="image">Image:
                                <input type="text" name="image" id="image">
                            </label>
                        </div>
                        <div class="col-md-1 col-sm-4">
                            <input type="submit" class="btn btn-primary" value="ADD">
                        </div>
                    </div>
                </form>
                <?php
                if ($_GET['msg'] == "fill_all") {
                    echo "<p class='text-center' style='color: red;' id='error'><b>Fill All Input</b></p>";
                }
                ?>
                <div class="row">
                    <?php
                    echo $blog;
                    ?>
                </div>
            </section>
            <!--Section: Content-->

        </div>
    </main>
    <!--Main layout-->

    <!--Footer-->
    <footer class="bg-light text-lg-start">
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            © 2020 Copyright:
            <a class="text-dark" href="">CEDCOSS.com</a>
        </div>
        <!-- Copyright -->
    </footer>
    <!--Footer-->
</body>